import "./globals.css";

export const metadata = {
  title: "고병연 신입 웹 개발자",
  description: "Generated by 병연",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
